/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CompletionUsage
 */
public class CompletionUsageTest {
    private final CompletionUsage model = new CompletionUsage();

    /**
     * Model tests for CompletionUsage
     */
    @Test
    public void testCompletionUsage() {
        // TODO: test CompletionUsage
    }

    /**
     * Test the property 'promptTokens'
     */
    @Test
    public void promptTokensTest() {
        // TODO: test promptTokens
    }

    /**
     * Test the property 'completionTokens'
     */
    @Test
    public void completionTokensTest() {
        // TODO: test completionTokens
    }

    /**
     * Test the property 'totalTokens'
     */
    @Test
    public void totalTokensTest() {
        // TODO: test totalTokens
    }

}
