/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.langchain4j.langsmith.model.Model;
import dev.langchain4j.langsmith.model.Prompt;
import dev.langchain4j.langsmith.model.Stop;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for CreateCompletionRequest
 */
public class CreateCompletionRequestTest {
    private final CreateCompletionRequest model = new CreateCompletionRequest();

    /**
     * Model tests for CreateCompletionRequest
     */
    @Test
    public void testCreateCompletionRequest() {
        // TODO: test CreateCompletionRequest
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'prompt'
     */
    @Test
    public void promptTest() {
        // TODO: test prompt
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'maxTokens'
     */
    @Test
    public void maxTokensTest() {
        // TODO: test maxTokens
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    public void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'topP'
     */
    @Test
    public void topPTest() {
        // TODO: test topP
    }

    /**
     * Test the property 'n'
     */
    @Test
    public void nTest() {
        // TODO: test n
    }

    /**
     * Test the property 'stream'
     */
    @Test
    public void streamTest() {
        // TODO: test stream
    }

    /**
     * Test the property 'logprobs'
     */
    @Test
    public void logprobsTest() {
        // TODO: test logprobs
    }

    /**
     * Test the property 'echo'
     */
    @Test
    public void echoTest() {
        // TODO: test echo
    }

    /**
     * Test the property 'stop'
     */
    @Test
    public void stopTest() {
        // TODO: test stop
    }

    /**
     * Test the property 'presencePenalty'
     */
    @Test
    public void presencePenaltyTest() {
        // TODO: test presencePenalty
    }

    /**
     * Test the property 'frequencyPenalty'
     */
    @Test
    public void frequencyPenaltyTest() {
        // TODO: test frequencyPenalty
    }

    /**
     * Test the property 'bestOf'
     */
    @Test
    public void bestOfTest() {
        // TODO: test bestOf
    }

    /**
     * Test the property 'logitBias'
     */
    @Test
    public void logitBiasTest() {
        // TODO: test logitBias
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
