/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Logprobs
 */
public class LogprobsTest {
    private final Logprobs model = new Logprobs();

    /**
     * Model tests for Logprobs
     */
    @Test
    public void testLogprobs() {
        // TODO: test Logprobs
    }

    /**
     * Test the property 'tokens'
     */
    @Test
    public void tokensTest() {
        // TODO: test tokens
    }

    /**
     * Test the property 'tokenLogprobs'
     */
    @Test
    public void tokenLogprobsTest() {
        // TODO: test tokenLogprobs
    }

    /**
     * Test the property 'topLogprobs'
     */
    @Test
    public void topLogprobsTest() {
        // TODO: test topLogprobs
    }

    /**
     * Test the property 'textOffset'
     */
    @Test
    public void textOffsetTest() {
        // TODO: test textOffset
    }

}
