/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import dev.langchain4j.langsmith.model.ModelAnyOfValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Model
 */
public class ModelTest {
    private final Model model = new Model();

    /**
     * Model tests for Model
     */
    @Test
    public void testModel() {
        // TODO: test Model
    }

}
