/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.langchain4j.langsmith.model.RunTypeEnum;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RunCreateSchema
 */
public class RunCreateSchemaTest {
    private final RunCreateSchema model = RunCreateSchema.builder().build();

    /**
     * Model tests for RunCreateSchema
     */
    @Test
    public void testRunCreateSchema() {
        // TODO: test RunCreateSchema
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'inputs'
     */
    @Test
    public void inputsTest() {
        // TODO: test inputs
    }

    /**
     * Test the property 'runType'
     */
    @Test
    public void runTypeTest() {
        // TODO: test runType
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'executionOrder'
     */
    @Test
    public void executionOrderTest() {
        // TODO: test executionOrder
    }

    /**
     * Test the property 'serialized'
     */
    @Test
    public void serializedTest() {
        // TODO: test serialized
    }

    /**
     * Test the property 'outputs'
     */
    @Test
    public void outputsTest() {
        // TODO: test outputs
    }

    /**
     * Test the property 'parentRunId'
     */
    @Test
    public void parentRunIdTest() {
        // TODO: test parentRunId
    }

    /**
     * Test the property 'manifestId'
     */
    @Test
    public void manifestIdTest() {
        // TODO: test manifestId
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'sessionName'
     */
    @Test
    public void sessionNameTest() {
        // TODO: test sessionName
    }

    /**
     * Test the property 'childRuns'
     */
    @Test
    public void childRunsTest() {
        // TODO: test childRuns
    }

    /**
     * Test the property 'referenceExampleId'
     */
    @Test
    public void referenceExampleIdTest() {
        // TODO: test referenceExampleId
    }

}
