/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Stop
 */
public class StopTest {
    private final Stop model = new Stop();

    /**
     * Model tests for Stop
     */
    @Test
    public void testStop() {
        // TODO: test Stop
    }

}
