/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import com.google.gson.annotations.SerializedName;
import lombok.Builder;
import lombok.Value;

/**
 * ChatCompletionResponseMessage
 */
@Value
@Builder
public class ChatCompletionResponseMessage {
  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  String role = "";

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  String content;

  public static final String SERIALIZED_NAME_FUNCTION_CALL = "function_call";
  @SerializedName(SERIALIZED_NAME_FUNCTION_CALL)
  ChatCompletionFunctionCall functionCall;

  
}

