/*
 * LangSmith
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.langchain4j.langsmith.model;

import com.google.gson.annotations.JsonAdapter;
import dev.langchain4j.langsmith.OutputsDataTypeAdapter;
import lombok.Builder;
import lombok.Singular;
import lombok.Value;

import java.util.Map;

/**
 * Outputs
 */
@Value
@Builder
@JsonAdapter(OutputsDataTypeAdapter.class)
public class Outputs {

  @Singular("data")
  Map<String,Object> data;

}

