groupId: org.bsc.langgraph4j
artifactId: langsmith-sdk
artifactVersion: 1.0.0-SNAPSHOT
snapshotVersion: true
artifactUrl: https://github.com/bsorrentino/langsmith4j-sdk
artifactDescription: Langsmith integration for Langgraph4j.
developerEmail: bartolomeo.sorrentino@gmail.com
developerName: bsorrentino	
#developerOrganization:	
#developerOrganizationUrl:	
licenseName: MIT	
licenseUrl: https://opensource.org/license/mit
scmConnection: scm:git:git@github.com:bsorrentino/langsmith4j-sdk.git
scmDeveloperConnection: scm:git:git@github.com:bsorrentino/langsmith4j-sdk.git
scmUrl: https://github.com/bsorrentino/langsmith4j-sdk.git


generatorName: java
library: native
inputSpec: api/openapi.json

# Select the complementary documentation annotation library. (Default: none)
#     none - Do not annotate Model and Api with complementary annotations.
#     swagger1 - Annotate Model and Api using the Swagger Annotations 1.x library.
#     swagger2 - Annotate Model and Api using the Swagger Annotations 2.x library.
annotationLibrary: none

apiPackage: org.bsc.langgraph4j.langsmith.gen.api
modelPackage: org.bsc.langgraph4j.langsmith.gen.model

# Option. Date library to use (Default: java8)
#     joda - Joda (for legacy app only)
#     legacy - Legacy java.util.Date
#     java8-localdatetime - Java 8 using LocalDateTime (for legacy app only)
#     java8 - Java 8 native JSR310 (preferred for jdk 1.8+)
dateLibrary: java8

# Enable OpenAPI Jackson Nullable library (Default: true)
openApiNullable: true

# If true, async handlers will be used, instead of the sync version (Default: false)
asyncNative: true

validateSpec: false

